### ISSUE TITLE
Backoff in `with_retries` is too short

### ISSUE THREAD

**Issue by 2rs2ts** [grosser/kubernetes_leader_election#1]
The default backoff configured here is too short: https://github.com/grosser/kubernetes_leader_election/blob/2f36e4b3bb6d7f0a533e1bfefac3447f2ea8257e/lib/kubernetes_leader_election.rb#L126

In a particularly busy cluster, the race conditions this function is trying to work around will take longer to resolve than the couple of seconds trying three times with such short sleeps will net you. I don't know what went into the decision to use `0.1, 0.5, 1` as the sleep intervals, but I would be flabbergasted if even in a cluster with relatively low load, a 0.1 second sleep would ever help. Would you consider something more along the lines of `0.5, 1, 2`? Alternatively, making it configurable via an argument would be nice, but at that point, the user might as well just add in their own retry logic to wrap the call to `become_leader`.

**Comment by grosser** [comment]
longer wait times seem fine since this is not a very time critical part, PR welcome
maybe `[0.1, 0.5, 1, 2, 4]`
... allowing to configure is also fine

**Comment by 2rs2ts** [comment]
I can PR the code, gotta get clearance with my employer first though.
